volumes:
  postgres_data:
  redis_data:


services:

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped # Restart Policy Cheat Sheet:
                            # no               → Never restart. On exit (any reason), Docker does nothing.
                            # always           → Always restart, even after manual `docker stop` or reboot.
                            # unless-stopped   → Restart on crash or reboot, but NOT if manually stopped.
                            # on-failure[:N]   → Restart only if exit code ≠ 0. Optional N = max retries.

    env_file: .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:8.10.1
    restart: unless-stopped # Restart Policy Cheat Sheet:
                            # no               → Never restart. On exit (any reason), Docker does nothing.
                            # always           → Always restart, even after manual `docker stop` or reboot.
                            # unless-stopped   → Restart on crash or reboot, but NOT if manually stopped.
                            # on-failure[:N]   → Restart only if exit code ≠ 0. Optional N = max retries.

    env_file: .env

    environment:
      ALLOW_EMPTY_PASSWORD: "yes"

    volumes:
      - redis_data:/data

  infisical:
    image: infisical/infisical:v0.165.6
    restart: unless-stopped # Restart Policy Cheat Sheet:
                            # no               → Never restart. On exit (any reason), Docker does nothing.
                            # always           → Always restart, even after manual `docker stop` or reboot.
                            # unless-stopped   → Restart on crash or reboot, but NOT if manually stopped.
                            # on-failure[:N]   → Restart only if exit code ≠ 0. Optional N = max retries.

    env_file: .env

    environment:
      NODE_ENV: production

    ports:
      - "80:8080"

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
