FROM openresty/openresty:alpine-fat

RUN apk add --no-cache make gcc musl-dev postgresql-dev git openssl-dev libc-dev

RUN luarocks install lua-resty-openssl

RUN luarocks install lpeg

RUN luarocks install pgmoon

RUN luarocks install lua-resty-openidc

RUN mkdir -p /usr/local/openresty/lua

RUN mkdir -p /var/log/nginx

WORKDIR /usr/local/openresty

